
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[487] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       77,   75,   76,   75,   41,   41,   75,   75,   50,   41,
       41,   75,   50,   50,   50,   75,   75,   41,   41,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   45,   75,   41,   41,   75,   45,   45,   45,
       45,   45,   45,   39,   75,   75,   41,   42,    0,    0,
        0,    0,    0,   14,   15,   16,   28,    0,   41,    0,
        0,    0,    0,    0,    0,    0,   42,    0,   41,    0,
        0,    0,    0,   62,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   45,   44,   45,
        0,    0,    0,    0,   41,   45,   44,   45,   45,   45,
       32,   45,   45,   45,   45,   45,   45,   45,   33,   45,
       37,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       11,    0,    0,   27,   40,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   42,    0,   69,    0,    0,    0,
        0,   71,    0,    0,   59,    0,   66,    0,    0,    0,
        0,    0,    0,   43,   40,   45,   31,   34,   33,   33,
       33,   35,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    8,    8,    0,    0,   11,    0,    0,

        0,    0,   26,    2,    0,    0,    0,    0,    1,   49,
        0,    0,   47,    0,    0,    0,   68,    0,    0,   67,
        0,    0,    0,    0,    0,   56,    0,   70,    0,    0,
       45,   34,   34,   34,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   10,   10,   10,   10,    8,    0,
        7,    7,    7,    3,    5,    6,    4,   48,   46,    0,
        0,    0,   61,    0,    0,   67,    0,    0,    0,    0,
       55,    0,    0,   45,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    0,    0,    0,
        0,    0,    0,   58,    0,    0,   54,    0,    0,   45,

       38,    0,   12,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   72,   74,    0,    0,    0,    0,    0,   51,
        0,   45,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   73,    0,    0,    0,    0,    0,    0,
       45,    0,    0,    0,    0,    0,    0,    0,   25,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   13,   18,   17,    0,    0,    0,    0,    0,    0,
       63,    0,    0,    0,    0,   36,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   22,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   57,    0,

       21,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   21,   21,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   60,    0,    0,    0,    0,   30,    0,    0,   53,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       29,    0,    0,   19,   52,    0,    0,    0,    0,   20,
        0,    0,   23,   23,    0,   20,   20,    0,    0,   23,
        0,    0,    0,    0,    0,   65,    0,    0,    0,    0,
        0,   64,   24,   24,   24,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    5,    1,    1,    1,    6,
        7,    8,    9,    7,   10,   11,    1,   12,   13,   14,
       15,   16,   14,   17,   18,   19,   20,   21,    1,    1,
       22,    1,    5,   23,   24,   24,   24,   24,   24,   24,
       25,   25,   26,   25,   25,   25,   25,   27,   25,   25,
       28,   25,   29,   30,   25,   25,   25,   31,   25,   25,
       32,   33,    1,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   25,   45,   46,   47,   48,
       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,    1,   34,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[61] =
    {   0,
        1,    2,    3,    1,    4,    1,    1,    5,    6,    1,
        7,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        9,    1,    5,   10,   11,   11,   11,   11,   11,   11,
       11,    1,   12,    5,   11,   10,   10,   10,   10,   10,
       10,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11
    } ;

static yyconst flex_uint16_t yy_base[518] =
    {   0,
        0,   36,    9,   20,   72,  124,  170,    0,  227,    0,
       63,  115,  284,    0,   21,   24,   20,   25,  316,  344,
     1119, 1120, 1120,   68,    8,    0, 1068,    9, 1120,   10,
        0, 1059, 1067, 1060, 1074,   31,    0,   13, 1102, 1083,
     1059,   16, 1072,   25, 1061, 1064, 1071, 1052,    2,   41,
     1057,   20,    0,   16,   87,  373,    0,  284,  389,  304,
      444,  114,  158, 1120,    0, 1051, 1120, 1092,  110, 1081,
     1080, 1051, 1078, 1120, 1120, 1120, 1042,    0,    0,   36,
        0, 1047, 1049, 1041, 1065, 1044, 1081,    0, 1080, 1036,
     1047, 1036, 1033, 1120, 1039, 1036, 1030, 1045, 1027,    8,

     1027, 1036, 1043, 1028, 1033, 1036, 1023, 1065, 1120, 1064,
       17, 1069,  163,  495, 1068,   72,  121,  343,  372,  403,
      448,  501,  557,  519,  545,  582,  601,  652,  357,  415,
     1120, 1025, 1023, 1025,   17, 1020,  103, 1017, 1017,  697,
        0, 1016,  170, 1007,    0, 1040,  362, 1039,    0, 1001,
     1009, 1052, 1003, 1001,    0, 1003,   82, 1008, 1013, 1002,
      999, 1120,  998,  996, 1120,  998, 1120,  997, 1008, 1005,
     1006,  995, 1003, 1120,    0,  327,  422,  460,  448,  513,
      537,  615,  997,  994,  995, 1002,  990,  981,  988,  998,
     1023,  992,  160,  555,  724,  183,  625,    0,  977,  204,

      638,  590, 1120, 1120, 1008, 1007, 1006, 1005, 1120, 1120,
     1020, 1019, 1120,  972,  986,  978, 1120, 1000,  984, 1120,
      984,  979,  968,  976,  963,  979,  973, 1120,  963,  976,
      687,  707,  667,  713,  960,  956,  962,  961,  956,  959,
      960,  964,  954,  991,    0,  210,  641,  753,    0,  987,
        0,  338,  741, 1120, 1120, 1120, 1120, 1120, 1120,  950,
      941,  936, 1120,  930,  937,  944,  895,  922,  887,  871,
      896,  873,  865,  766,  879,  840,  859,  849,  882,  853,
      830,  831,  834,  819,    0,  820,  823,  827,  818,  788,
      774,  809,  774, 1120,  785,  767, 1120,  780,  783,  771,

     1120,  771, 1120,  768,  438,  762,  805,  766,  756,  767,
      755,  767, 1120, 1120,  773,  759,  759,  752,  736, 1120,
      717,  783,  724,  722,  708,  716,  708,  705,  697,  707,
      738,  700,  698, 1120,  690,  655,  653,  667,  660,  651,
      791,  646,  684,  638,  649,  640,  634,  633, 1120,  646,
      638,  667,  636,  649,  634,  619,  625,  617,  652,  607,
      611, 1120, 1120, 1120,  634,  607,  593,  631,  579,  569,
     1120,  576,  570,  568,  573, 1120,  556,  556,  552,  564,
      552,  571,  549,  537,  551,  535,  532,  540,  553,  533,
      531,  529,  514,  538,  510,  523,  494,  492, 1120,  503,

      520,  505,  477,  513,  472,  490,  478,  480,  449,  443,
      448,    0,    0,  450,  439,  442,  443,  455,  433,  422,
      428,  444,  410,  448,  410,  410,  406,  435,  405,  397,
      388, 1120,  374,  371,  370,  364, 1120,  378,  397, 1120,
      359,  369,  354,  341,  326,  329,  341,  328,  140,  347,
     1120,  325,  334, 1120, 1120,  311,  289,  307,  275,  288,
      271,  258, 1120,    0,  257,    0,    0,  239,  252,    0,
      186,  170,  180,  147,  140, 1120,  120,  117,  140,  139,
      117, 1120, 1120,    0,    0, 1120,  828,  840,  112,  101,
      846,  851,  858,  866,  875,  880,  883,  886,  100,  894,

      903,  910,  922,  929,  934,  939,  945,  952,  958,  964,
      969,  978,   89,  988,   52,   37,    0
    } ;

static yyconst flex_int16_t yy_def[518] =
    {   0,
      487,  487,  487,  487,  488,  488,    2,    7,  486,    9,
        9,    9,    2,   13,    2,    2,    2,    2,    2,    2,
      486,  486,  486,  486,  486,  489,  486,  486,  486,  486,
      489,  486,  486,  486,  486,  486,  490,  490,  491,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  492,  493,  493,  493,  494,  495,  495,  495,
      495,   61,   61,  486,  496,  486,  486,  490,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  497,  489,  486,
      498,  486,  486,  486,  486,  486,  490,  499,  491,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,

      486,  486,  486,  486,  486,  486,  486,  492,  486,  492,
      493,  500,  493,   56,   56,  492,  493,  501,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,  128,  128,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  502,
      503,  486,  504,  486,  497,  486,  486,  486,  505,  486,
      486,  486,  486,  486,  499,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  114,  128,  128,  128,  128,  128,
      128,  128,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  506,  507,  507,  502,  507,  503,  486,  508,

      509,  504,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      128,  128,  128,  128,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  510,  506,  507,  195,  195,  486,
      511,  508,  509,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  128,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  248,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  128,

      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  128,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      128,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,

      512,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  512,  512,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  513,  486,  514,
      486,  486,  486,  515,  486,  514,  514,  486,  486,  515,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      516,  486,  486,  517,  517,    0,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,

      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486
    } ;

static yyconst flex_uint16_t yy_nxt[1181] =
    {   0,
      486,   23,  486,  486,  486,  486,  486,  485,  109,   24,
       23,   25,   26,   26,   26,   26,   26,   26,   26,   26,
       28,   23,  110,   88,  111,  111,  112,  112,  165,   22,
       22,   28,   67,   22,   22,   67,   27,   23,   78,   78,
       78,  101,  166,   78,  484,   24,  102,   25,   26,   26,
       26,   26,   26,   26,   26,   26,   22,   22,   85,  470,
       22,   22,  106,  186,   92,   78,   78,   78,  107,   86,
       78,  187,   27,   23,   93,   22,  146,   69,   22,   95,
      109,   96,  147,   30,   31,   31,   31,   31,   31,   31,
       31,   31,  103,  148,  110,  111,  464,  112,   60,  104,

       60,   60,   61,   70,   32,   71,   72,  155,   87,   33,
       34,   60,   60,   73,   62,   63,  217,  114,   74,   79,
       75,   76,   60,   77,   35,   23,  128,   22,  483,  111,
       22,  112,  129,  129,  218,   30,   31,   31,   31,   31,
       31,   31,   31,   31,  114,  133,  189,  134,  135,  136,
       60,  190,   60,   60,   61,  137,   32,  138,  139,  482,
      481,   33,   34,   60,   60,  174,   62,   63,  193,  480,
      245,  111,  479,  112,   60,  456,   35,   36,  200,   37,
      457,   38,   39,   39,   39,   39,   39,   39,   39,   39,
      202,  193,  478,  119,  119,  119,  119,   40,  121,  477,

      476,  119,  202,  196,  200,   41,   42,   43,   44,  475,
      119,  130,  200,   45,  251,  196,   46,  193,  193,   47,
      245,   48,   49,   50,   51,  474,   52,   22,   23,   22,
       22,   53,   22,   22,   22,   54,   22,   22,   55,   56,
       56,   56,   56,   56,   56,   56,   56,   22,   22,   57,
       58,   58,   58,   58,   58,   58,   58,   58,   22,   53,
       22,   58,   58,   59,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   64,  108,  473,
      472,  108,  117,   22,  118,   65,   65,   65,   65,   65,

       65,   65,   65,   65,  471,  469,  110,   65,  108,  468,
      467,  108,  117,  465,  118,   66,  108,  108,  463,   65,
       65,   65,   65,   65,   65,   37,  110,   68,   68,   68,
       68,   68,   68,   68,   68,   68,  108,  108,  119,  119,
      119,  119,  119,  462,  121,  174,  200,  108,  251,  461,
      108,  109,   22,   37,  460,   68,   68,   68,   68,   68,
       68,   68,   68,   68,  459,  108,  231,  458,  119,  119,
      119,  119,  119,  455,  174,  108,  108,  454,  453,  452,
       22,  111,  451,  112,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  108,  108,  179,  108,  117,  205,  118,

      206,  450,  180,  449,  448,  174,  447,  119,  119,  119,
      119,  110,  207,  181,  446,  119,  445,  444,  208,  443,
      442,  108,  108,  441,  119,  108,  182,  182,  182,  182,
      182,  182,  182,  119,  119,  119,  119,  119,  119,  119,
      119,  119,  440,  439,  438,  437,  119,  120,  108,  436,
      174,  108,  117,  435,  118,  119,  176,  434,  433,  119,
      119,  119,  119,  119,  432,  431,  110,  430,  429,  428,
      108,  119,  119,  119,  119,  119,  108,  108,  325,  122,
      123,  124,  125,  119,  119,  119,  119,  126,  427,  426,
      326,  119,  425,  180,  424,  327,  127,  174,  232,  423,

      119,  422,  421,  174,  181,  233,  175,  175,  175,  175,
      175,  175,  175,  175,  175,  420,  234,  419,  175,  418,
      417,  174,  416,  108,  119,  119,  119,  119,  119,  415,
      175,  175,  175,  175,  175,  175,  119,  119,  119,  119,
      414,  108,  413,  411,  119,  410,  409,  174,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  177,  174,
      408,  407,  119,  193,  406,  245,  405,  108,  404,  181,
      403,  119,  402,  401,  400,  196,  177,  399,  398,  108,
      119,  119,  119,  119,  174,  248,  397,  196,  177,  246,
      396,  395,  119,  119,  119,  119,  394,  119,  200,  393,

      119,  392,  177,  174,  108,  391,  177,  390,  389,  119,
      202,  388,  248,  387,  177,  386,  385,  119,  119,  119,
      119,  384,  202,  108,  200,  119,  119,  119,  119,  119,
      119,  177,  383,  193,  119,  245,  119,  119,  119,  119,
      382,  381,  380,  379,  177,  196,  200,  378,  251,  193,
      177,  245,  377,  119,  174,  376,  375,  196,  202,  246,
      374,  196,  373,  178,  178,  178,  178,  178,  372,  371,
      202,  370,  252,  196,  108,  246,  369,  368,  119,  119,
      119,  119,  119,  367,  366,  365,  364,  119,  119,  119,
      119,  363,  362,  361,  360,  119,  358,  357,  119,  119,

      119,  119,  119,  356,  119,  193,  355,  354,  194,  195,
      195,  195,  195,  195,  195,  195,  195,  196,  119,  119,
      119,  119,  119,  234,  119,  119,  119,  119,  119,  196,
      353,  193,  193,  274,  245,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  196,  352,  351,  350,  349,  200,
      348,  251,  233,  347,  346,  345,  196,  344,  246,  343,
      342,  202,  340,  234,  285,  285,  285,  285,  285,  285,
      285,  285,  285,  202,  339,  252,  285,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  338,  285,  285,
      285,  285,  285,  285,  119,  119,  119,  119,  119,  337,

      336,  300,  119,  119,  119,  119,  119,  335,  334,  333,
      332,  359,  331,  330,  329,  328,  324,  323,  321,  320,
      319,  318,  317,  322,  220,  316,  315,  341,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   89,   89,  108,  108,  108,  108,  108,  314,
      108,  108,  108,  113,  113,  113,  313,  113,  113,  116,
      312,  311,  310,  309,  308,  116,  116,  116,  119,  119,
      119,  119,  119,  307,  119,  119,  119,  131,  306,  131,
      145,  305,  145,  149,  304,  149,  112,  303,  302,  301,

      112,  112,  299,  112,  112,  118,  118,  118,  118,  118,
      118,  298,  118,  118,  118,  197,  297,  197,  197,  197,
      197,  197,  198,  296,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  201,  295,  201,  201,  201,  201,
      201,  210,  294,  210,  246,  246,  246,  293,  246,  246,
      247,  247,  247,  247,  247,  247,  247,  252,  252,  252,
      292,  252,  252,  253,  253,  253,  253,  253,  253,  253,
      245,  245,  291,  245,  245,  251,  251,  290,  251,  251,
      412,  412,  412,  289,  412,  412,  288,  412,  412,  412,
      466,  466,  466,  287,  466,  466,  286,  466,  466,  466,

      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,
      250,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  220,  230,  229,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  219,  216,  215,  214,  213,  212,  211,
      209,  204,  203,  199,  192,  191,  188,  185,  184,  183,
      174,  174,  109,  109,  173,  172,  171,  170,  169,  168,
      167,  164,  163,  162,  161,  160,  159,  158,  157,  156,
       88,   88,  154,  153,  152,  151,  150,  144,  143,  142,

      141,  140,   88,  132,  105,  100,   99,   98,   97,   94,
       91,   90,   88,   84,   83,   82,   81,   80,  486,   21,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486
    } ;

static yyconst flex_int16_t yy_chk[1181] =
    {   0,
        0,    1,    0,    0,    0,    0,    0,  517,   53,    1,
        3,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,   53,   38,   54,  111,   54,  111,  100,   17,
       15,    4,   15,   16,   18,   16,    1,    2,   25,   28,
       30,   49,  100,   38,  516,    2,   49,    2,    2,    2,
        2,    2,    2,    2,    2,    2,   17,   15,   36,  515,
       16,   18,   52,  135,   42,   25,   28,   30,   52,   36,
       38,  135,    2,    5,   42,    5,   80,   24,    5,   44,
      116,   44,   80,    5,    5,    5,    5,    5,    5,    5,
        5,    5,   50,   80,  116,   55,  513,   55,   11,   50,

       11,   11,   11,   24,    5,   24,   24,  499,  490,    5,
        5,   11,   11,   24,   11,   11,  157,   55,   24,  489,
       24,   24,   11,   24,    5,    6,   62,    6,  481,  117,
        6,  117,   62,   62,  157,    6,    6,    6,    6,    6,
        6,    6,    6,    6,   55,   69,  137,   69,   69,   69,
       12,  137,   12,   12,   12,   69,    6,   69,   69,  480,
      479,    6,    6,   12,   12,  113,   12,   12,  193,  478,
      193,  113,  477,  113,   12,  449,    6,    7,  143,    7,
      449,    7,    7,    7,    7,    7,    7,    7,    7,    7,
      143,  196,  475,   63,   63,   63,   63,    7,   63,  474,

      473,   63,  143,  196,  143,    7,    7,    7,    7,  472,
       63,   63,  200,    7,  200,  196,    7,  196,  246,    7,
      246,    7,    7,    7,    7,  471,    7,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   13,   58,  469,
      468,   58,   58,   13,   58,   13,   13,   13,   13,   13,

       13,   13,   13,   13,  465,  462,   58,   13,   60,  461,
      460,   60,   60,  459,   60,   13,   58,   58,  458,   13,
       13,   13,   13,   13,   13,   19,   60,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   60,   60,  176,  176,
      176,  176,  176,  457,   60,  118,  252,  118,  252,  456,
      118,  118,   19,   20,  453,   20,   20,   20,   20,   20,
       20,   20,   20,   20,  452,  118,  176,  450,  129,  129,
      129,  129,  129,  448,  119,  118,  118,  447,  446,  445,
       20,   56,  444,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   59,  119,  129,   59,   59,  147,   59,

      147,  443,  129,  442,  441,  120,  439,  119,  119,  119,
      119,   59,  147,  129,  438,  119,  436,  435,  147,  434,
      433,   59,   59,  431,  119,  120,  130,  130,  130,  130,
      130,  130,  130,  177,  177,  177,  177,  177,  120,  120,
      120,  120,  430,  429,  428,  427,  120,   59,   61,  426,
      121,   61,   61,  425,   61,  120,  120,  424,  423,  179,
      179,  179,  179,  179,  422,  421,   61,  420,  419,  418,
      121,  178,  178,  178,  178,  178,   61,   61,  305,   61,
       61,   61,   61,  121,  121,  121,  121,   61,  417,  416,
      305,  121,  415,  179,  414,  305,   61,  114,  178,  411,

      121,  410,  409,  122,  179,  178,  114,  114,  114,  114,
      114,  114,  114,  114,  114,  408,  178,  407,  114,  406,
      405,  124,  404,  122,  180,  180,  180,  180,  180,  403,
      114,  114,  114,  114,  114,  114,  122,  122,  122,  122,
      402,  124,  401,  400,  122,  398,  397,  125,  181,  181,
      181,  181,  181,  122,  124,  124,  124,  124,  122,  123,
      396,  395,  124,  194,  394,  194,  393,  125,  392,  180,
      391,  124,  390,  389,  388,  194,  124,  387,  386,  123,
      125,  125,  125,  125,  126,  194,  385,  194,  125,  194,
      384,  383,  123,  123,  123,  123,  382,  125,  202,  381,

      123,  380,  125,  127,  126,  379,  123,  378,  377,  123,
      202,  375,  194,  374,  123,  373,  372,  126,  126,  126,
      126,  370,  202,  127,  202,  126,  182,  182,  182,  182,
      182,  126,  369,  197,  126,  197,  127,  127,  127,  127,
      368,  367,  366,  365,  127,  197,  201,  361,  201,  247,
      127,  247,  360,  127,  128,  359,  358,  197,  201,  197,
      357,  247,  356,  128,  128,  128,  128,  128,  355,  354,
      201,  353,  201,  247,  128,  247,  352,  351,  233,  233,
      233,  233,  233,  350,  348,  347,  346,  128,  128,  128,
      128,  345,  344,  343,  342,  128,  340,  339,  231,  231,

      231,  231,  231,  338,  128,  140,  337,  336,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  232,  232,
      232,  232,  232,  233,  234,  234,  234,  234,  234,  140,
      335,  140,  195,  231,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  333,  332,  331,  330,  253,
      329,  253,  232,  328,  327,  326,  195,  325,  195,  324,
      323,  253,  321,  232,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  253,  319,  253,  248,  274,  274,  274,
      274,  274,  300,  300,  300,  300,  300,  318,  248,  248,
      248,  248,  248,  248,  322,  322,  322,  322,  322,  317,

      316,  274,  341,  341,  341,  341,  341,  315,  312,  311,
      310,  341,  309,  308,  307,  306,  304,  302,  299,  298,
      296,  295,  293,  300,  292,  291,  290,  322,  487,  487,
      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      488,  488,  488,  488,  488,  488,  488,  488,  488,  488,
      488,  488,  491,  491,  492,  492,  492,  492,  492,  289,
      492,  492,  492,  493,  493,  493,  288,  493,  493,  494,
      287,  286,  284,  283,  282,  494,  494,  494,  495,  495,
      495,  495,  495,  281,  495,  495,  495,  496,  280,  496,
      497,  279,  497,  498,  278,  498,  500,  277,  276,  275,

      500,  500,  273,  500,  500,  501,  501,  501,  501,  501,
      501,  272,  501,  501,  501,  502,  271,  502,  502,  502,
      502,  502,  503,  270,  503,  503,  503,  503,  503,  503,
      503,  503,  503,  503,  504,  269,  504,  504,  504,  504,
      504,  505,  268,  505,  506,  506,  506,  267,  506,  506,
      507,  507,  507,  507,  507,  507,  507,  508,  508,  508,
      266,  508,  508,  509,  509,  509,  509,  509,  509,  509,
      510,  510,  265,  510,  510,  511,  511,  264,  511,  511,
      512,  512,  512,  262,  512,  512,  261,  512,  512,  512,
      514,  514,  514,  260,  514,  514,  250,  514,  514,  514,

      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      230,  229,  227,  226,  225,  224,  223,  222,  221,  219,
      218,  216,  215,  214,  212,  211,  208,  207,  206,  205,
      199,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  173,  172,  171,  170,  169,  168,  166,  164,  163,
      161,  160,  159,  158,  156,  154,  153,  152,  151,  150,
      148,  146,  144,  142,  139,  138,  136,  134,  133,  132,
      115,  112,  110,  108,  107,  106,  105,  104,  103,  102,
      101,   99,   98,   97,   96,   95,   93,   92,   91,   90,
       89,   87,   86,   85,   84,   83,   82,   77,   73,   72,

       71,   70,   68,   66,   51,   48,   47,   46,   45,   43,
       41,   40,   39,   35,   34,   33,   32,   27,   21,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486,
      486,  486,  486,  486,  486,  486,  486,  486,  486,  486
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "opts_scan.l"
#line 2 "opts_scan.l"

/*
 *  _______                      
 * |__   __|                     
 *    | |_ __ __ _  ___ ___ _ __ 
 *    | | '__/ _` |/ __/ _ \ '__|
 *    | | | | (_| | (_|  __/ |   
 *    |_|_|  \__,_|\___\___|_|   
 *
 * Written by Dennis Yurichev <dennis(a)yurichev.com>, 2013
 *
 * This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License. 
 * To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/.
 *
 */

#include "oassert.h"
#include "ostrings.h"
#include "BPF.h"

#include "stuff.h"
#include "dmalloc.h"
#include "X86_register.h"

//#include "opts_parse.h"
#include "opts_aux.h"
#include "opts_parse.tab.h"

// BCC mangled names may be started with @

// must support multiple dots in filename like Software.v3.2.1.exe




#line 929 "lex.yy.c"

#define INITIAL 0
#define STATE_BPM 1
#define STATE_BPX 2
#define STATE_BPF 3
#define STATE_ADDRESS 4
#define STATE_ADDRESS_OR_REG 5
#define STATE_BYTEMASK 6
#define STATE_BYTEMASK_SKIP_OPT 7
#define STATE_READ_ADR_OFS 8
#define STATE_FLOAT_NUMBER 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int _new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 54 "opts_scan.l"


#line 1169 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 487 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1120 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 56 "opts_scan.l"
{ BEGIN(STATE_BPX); yy_push_state(STATE_ADDRESS); return BPX_EQ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "opts_scan.l"
{ 
    oassert (current_BPF==NULL); 
    current_BPF=DCALLOC (struct BPF, 1, "BPF"); 
    BEGIN(STATE_BPF); 
    yy_push_state(STATE_ADDRESS); 
    return BPF_EQ; 
    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "opts_scan.l"
{ yylval.num=1; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "opts_scan.l"
{ yylval.num=2; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "opts_scan.l"
{ yylval.num=4; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 67 "opts_scan.l"
{ yylval.num=8; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 68 "opts_scan.l"
{ yylval.str=DSTRDUP(yytext+3, "yytext"); return LOAD_FILENAME; };
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "opts_scan.l"
{ yylval.num=strtol(yytext+3, NULL, 10); return ATTACH_PID; };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 70 "opts_scan.l"
{ yylval.num=strtol(yytext+3, NULL, 16); return ATTACH_PID; };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 71 "opts_scan.l"
{ yylval.str=DSTRDUP(yytext+3, "yytext"); return ATTACH_FILENAME; };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 72 "opts_scan.l"
{ 
    yylval.str=DSTRDUP(yytext+3, "yytext"); 
    //str_trim_all_lf_cr_right(yylval.str); 
    remove_char_begin_end_if_present(yylval.str, '"');
    return CMDLINE; 
    };
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 78 "opts_scan.l"
{ return CHILD; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "opts_scan.l"
{ return DUMP_FPU; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 80 "opts_scan.l"
{ return DASH_Q; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "opts_scan.l"
{ return DASH_S; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 82 "opts_scan.l"
{ return DASH_T; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 83 "opts_scan.l"
{ return DUMP_XMM; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "opts_scan.l"
{ return DUMP_SEH; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "opts_scan.l"
{ return DONT_RUN_THREAD_B; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "opts_scan.l"
{
        yylval.str=DSTRDUP(yytext+strlen("--one-time-INT3-bp:"), "yytext");
        return ONE_TIME_INT3_BP;
    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 90 "opts_scan.l"
{
        yylval.str=DSTRDUP(yytext+strlen("--allsymbols:"), "yytext"); 
        //printf ("--allsymbols: [%s]\n", yylval.str);
        return ALL_SYMBOLS; 
    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 95 "opts_scan.l"
{
        yylval.str=NULL; 
        return ALL_SYMBOLS; 
    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 99 "opts_scan.l"
{
        yylval.num=strtol(yytext+19, NULL, 10); 
        return DMALLOC_BREAK_ON;
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "opts_scan.l"
{
        yylval.num=strtol(yytext+25, NULL, 10); 
        return LIMIT_TRACE_NESTEDNESS;
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 107 "opts_scan.l"
{ return LOADING; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 108 "opts_scan.l"
{ return VERBOSE3; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 109 "opts_scan.l"
{ return VERBOSE2; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 110 "opts_scan.l"
{ return VERBOSE1; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 111 "opts_scan.l"
{ return EMULATOR_TESTING; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 112 "opts_scan.l"
{ return NO_NEW_CONSOLE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 114 "opts_scan.l"
{ yylval.x86reg=X86_register_from_string(yytext); yy_pop_state(); return REGISTER; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 115 "opts_scan.l"
{ yylval.x86reg=X86_register_from_string(yytext); yy_pop_state(); return REGISTER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 116 "opts_scan.l"
{ yylval.x86reg=X86_register_from_string(yytext); yy_pop_state(); return REGISTER; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 117 "opts_scan.l"
{ yylval.x86reg=X86_register_from_string(yytext); return REGISTER; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 118 "opts_scan.l"
{ yylval.x86reg=X86_register_from_string(yytext); BEGIN(STATE_FLOAT_NUMBER); return FPU_REGISTER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 120 "opts_scan.l"
{ yy_push_state(STATE_BYTEMASK); return BYTEMASK; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 121 "opts_scan.l"
{ yylval.num = strtol(yytext, NULL, 16); return HEX_BYTE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 122 "opts_scan.l"
{ yy_push_state(STATE_BYTEMASK_SKIP_OPT); return SKIP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 123 "opts_scan.l"
{ 
    if (YYSTATE==STATE_BYTEMASK)
    {
        yy_pop_state(); /* switch back to STATE_ADDRESS */
        yy_pop_state(); /* switch back to what was before */
    };
    return BYTEMASK_END; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 131 "opts_scan.l"
{
    if ((YYSTATE==STATE_ADDRESS) || (YYSTATE==STATE_READ_ADR_OFS))
        yy_pop_state(); /* switch back to what was before STATE_ADDRESS */
    yylval.num=strtol_or_strtoll(yytext, NULL, 16); 
    return HEX_NUMBER; 
   }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 137 "opts_scan.l"
{ 
    if (YYSTATE==STATE_READ_ADR_OFS || YYSTATE==STATE_BYTEMASK_SKIP_OPT)
        yy_pop_state(); /* switch back to what was before STATE_ADDRESS */
    yylval.num = strtol_or_strtoll(yytext, NULL, 10); 
    return DEC_NUMBER; 
   }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 143 "opts_scan.l"
{ 
    if (YYSTATE==STATE_FLOAT_NUMBER)
        yy_pop_state(); /* switch back to what was before */
    yylval.dbl = atof(yytext); 
    return FLOAT_NUMBER; 
   }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 149 "opts_scan.l"
{ yylval.str = DSTRDUP(yytext, "yytext"); str_trim_one_char_right(yylval.str); return FILENAME_EXCLAMATION; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 150 "opts_scan.l"
{ 
    BEGIN (STATE_READ_ADR_OFS);
    yylval.str = DSTRDUP(yytext, "yytext");
    str_trim_one_char_right(yylval.str);
    return SYMBOL_NAME_RE_PLUS; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 155 "opts_scan.l"
{ 
    yy_pop_state(); /* switch back to what was before STATE_ADDRESS */
    yylval.str = DSTRDUP(yytext, "yytext"); 
    return SYMBOL_NAME_RE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 160 "opts_scan.l"
{ yy_push_state(STATE_ADDRESS_OR_REG); return DUMP_OP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 161 "opts_scan.l"
{ yy_push_state(STATE_ADDRESS_OR_REG); return SET_OP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 162 "opts_scan.l"
{ yy_push_state(STATE_ADDRESS_OR_REG); return COPY_OP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 163 "opts_scan.l"
{ yylval.num = strtol(yytext+2, NULL, 16); return CSTRING_BYTE ; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 164 "opts_scan.l"
{ yylval.num = yytext[0]; return CSTRING_BYTE ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 166 "opts_scan.l"
{ return BPF_UNICODE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 167 "opts_scan.l"
{ return BPF_MICROSOFT_FASTCALL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 168 "opts_scan.l"
{ return BPF_BORLAND_FASTCALL; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 169 "opts_scan.l"
{ return BPF_TRACE_COLON; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 170 "opts_scan.l"
{ return BPF_TRACE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 171 "opts_scan.l"
{ return BPF_SKIP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 172 "opts_scan.l"
{ return BPF_SKIP_STDCALL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 173 "opts_scan.l"
{ return BPF_PAUSE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 174 "opts_scan.l"
{ return BPF_RT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 175 "opts_scan.l"
{ return BPF_RT_PROBABILITY; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 176 "opts_scan.l"
{ return BPF_ARGS; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 177 "opts_scan.l"
{ return BPF_CC; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 178 "opts_scan.l"
{ return BPF_DUMP_ARGS; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 179 "opts_scan.l"
{ yy_push_state(STATE_ADDRESS); return WHEN_CALLED_FROM_ADDRESS; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 180 "opts_scan.l"
{ yy_push_state(STATE_ADDRESS); return WHEN_CALLED_FROM_FUNC; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 181 "opts_scan.l"
{ return SET; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 182 "opts_scan.l"
{ 
    if (stricmp(yytext, "byte")==0) { yylval.num=1; return BYTE_WORD_DWORD_DWORD64; };
    if (stricmp(yytext, "word")==0) { yylval.num=2; return BYTE_WORD_DWORD_DWORD64; };
    if (stricmp(yytext, "dword")==0) { yylval.num=4; return BYTE_WORD_DWORD_DWORD64; };
    if (stricmp(yytext, "dword64")==0) { yylval.num=8; return BYTE_WORD_DWORD_DWORD64; };
    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 188 "opts_scan.l"
{ return ARG_; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 189 "opts_scan.l"
{ return ARG; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 190 "opts_scan.l"
{ return TYPE; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 191 "opts_scan.l"
{ return TYPE_INT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 192 "opts_scan.l"
{ return TYPE_PTR_TO_DOUBLE;  /* FIXME: do something with asterisk! */ }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 193 "opts_scan.l"
{ return TYPE_PTR_TO_QSTRING; /* FIXME: do something with asterisk! */ }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 194 "opts_scan.l"
{ return TYPE_QSTRING; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 196 "opts_scan.l"
{ 
    //fprintf (stderr, "Catch-all symbol: '%c'\n", yytext[0]); 
    return yytext[0]; 
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 200 "opts_scan.l"
ECHO;
	YY_BREAK
#line 1669 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_BPM):
case YY_STATE_EOF(STATE_BPX):
case YY_STATE_EOF(STATE_BPF):
case YY_STATE_EOF(STATE_ADDRESS):
case YY_STATE_EOF(STATE_ADDRESS_OR_REG):
case YY_STATE_EOF(STATE_BYTEMASK):
case YY_STATE_EOF(STATE_BYTEMASK_SKIP_OPT):
case YY_STATE_EOF(STATE_READ_ADR_OFS):
case YY_STATE_EOF(STATE_FLOAT_NUMBER):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 487 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 487 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 486);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 200 "opts_scan.l"



void flex_set_str(char *s)
{
    YY_BUFFER_STATE buf;
    buf=yy_scan_string (s);
    yy_switch_to_buffer (buf);
};

void flex_cleanup()
{
    yy_delete_buffer(YY_CURRENT_BUFFER );
};

void flex_restart()
{
    BEGIN(INITIAL);
};

/* vim: set expandtab ts=4 sw=4 : */

