#line 2 "opts.lex.c"

#line 4 "opts.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[268] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   67,   66,
       66,   36,   36,   66,   65,   41,   65,   65,   42,   50,
       50,   48,   47,   41,   36,   36,   65,   50,   50,   50,
       61,   36,   36,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   36,   36,   40,   65,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   33,   65,   65,   65,   34,
       36,   36,   36,    0,    0,    0,    0,    0,   36,    0,
       43,    0,    0,    0,    0,   37,    0,   36,    0,   60,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       36,   39,   40,   40,   40,   24,   27,   28,   40,   40,
       40,   40,   40,   40,   26,   22,   23,   25,   32,   30,
        0,    0,    0,   11,    0,   35,    0,    0,    0,    0,
        0,    0,    0,   37,    0,    0,    0,   57,    0,    0,
        0,    0,    0,    0,   35,   40,   13,   19,   14,   15,
       18,   16,   21,   17,   20,    0,    0,    8,    8,    0,
       11,    0,    2,    0,    0,    0,    0,    1,   49,    0,
        0,   45,    0,    0,    0,    0,   54,    0,    0,    0,
       38,   40,    0,    0,    0,    0,    8,    0,    3,    5,
        6,    4,   46,   44,   59,    0,    0,    0,    0,   53,

        0,    0,   40,    0,    0,   10,    9,    7,    0,   56,
        0,    0,   52,    0,    0,   40,   31,   12,    0,    0,
        0,   51,    0,   40,    0,    0,    0,    0,   40,    0,
        0,    0,    0,    0,   62,    0,    0,    0,   29,    0,
        0,    0,    0,   55,    0,    0,    0,    0,    0,   58,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   64,    0,    0,   63,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    1,    1,    6,
        7,    1,    8,    9,   10,   11,    1,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    1,    1,
       15,    1,    1,   16,   17,   17,   17,   17,   17,   17,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   18,   18,
       20,   21,   22,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   18,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   18,   44,   45,
       46,   47,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    3,    1,    1,
        4,    5,    5,    1,    1,    3,    5,    6,    6,    1,
        1,    1,    6,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[284] =
    {   0,
        0,    4,    6,   18,   61,  101,  141,    0,  185,    0,
      209,  233,  279,    0,    9,   21,   24,   26,  556,  557,
       21,   16,   28,  517,  557,  557,   24,  510,  557,  557,
      557,  557,  557,  557,   30,   39,  508,  515,  508,  522,
      557,   66,   78,  509,  522,  504,  522,  503,  511,  503,
      506,  510,   48,   83,   90,  529,  101,  107,  108,  122,
      301,  123,  133,  147,  148,  557,  528,    0,  497,  557,
      557,   41,   38,  511,  522,  521,  520,    0,   59,   31,
      557,    0,  495,  497,  489,   68,  158,  161,  500,  557,
      494,  485,  106,  495,  502,  493,  496,    0,  512,  332,

      227,  557,  124,  514,  233,  237,  247,  256,  257,  277,
      268,  278,  303,  339,  313,  323,  324,  354,  557,  557,
      488,  489,   87,    0,    0,    0,  504,  339,  503,    0,
      471,  478,  509,  113,  473,  475,  471,  557,  473,  472,
      483,  482,  471,  503,    0,  364,  365,  371,  377,  378,
      387,  388,  389,  398,  399,  473,  472,  232,  325,  492,
        0,  491,  557,  476,  470,  440,  432,  557,  557,  439,
      435,  557,  425,  411,  404,  390,  406,  400,  387,  398,
      557,  400,  380,  379,    0,  425,  340,    0,  557,  557,
      557,  557,  557,  557,  557,  388,  388,  364,  350,  376,

      357,  348,  409,  355,  341,    0,    0,    0,  327,  557,
      338,  312,  557,  320,  322,  415,  557,  557,  300,  296,
      291,  557,  282,  411,  259,  273,  271,  261,  432,  273,
      250,  254,  241,  262,  557,  228,  220,  225,  557,  210,
      200,  157,  136,  557,  146,  120,  121,  146,  120,  557,
      113,  122,   68,   94,   64,   77,   50,   44,   38,   28,
       34,    3,  557,    1,    5,  557,  557,  456,  462,  468,
      471,  475,    4,    2,    1,  477,  481,  483,  489,  491,
        0,  493,  495
    } ;

static yyconst flex_int16_t yy_def[284] =
    {   0,
      268,  268,  269,  269,  270,  270,  269,    7,  267,    9,
        9,    9,  269,   13,  269,  269,  269,  269,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  271,  271,  272,  271,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  267,  267,  273,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  274,  267,  267,
      267,  275,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  276,  271,  271,

      271,  267,  272,  277,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  267,  267,
      267,  267,  278,  279,  280,  274,  267,  267,  267,  281,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  276,  100,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  267,  267,  278,  278,  278,
      279,  280,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  272,  267,  267,  282,  278,  278,  283,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  272,  267,  267,  282,  186,  283,  267,  267,
      267,  267,  267,  267,  267,  272,  267,  267,  267,  267,
      267,  267,  267,  272,  267,  267,  267,  267,  272,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,    0,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267
    } ;

static yyconst flex_int16_t yy_nxt[605] =
    {   0,
      267,  267,  267,  267,  169,  130,  126,   20,  120,   21,
       20,   22,   23,   21,   26,   22,   23,   27,  266,   20,
       71,   72,   20,  267,   24,   20,   26,   20,   24,   27,
       74,  267,   71,   72,   78,   73,   72,   73,   72,   79,
       79,  265,   78,  264,   75,   28,   76,  263,   78,   29,
       79,   79,   79,   79,   77,  262,   78,   28,   98,  127,
       78,   29,   31,  261,   32,  128,  100,   33,   78,   34,
       79,   79,   35,   36,   78,  129,   86,   87,   87,  134,
      134,   37,   78,  260,   78,  259,   38,   39,   86,   88,
       88,  254,  100,   98,  101,  101,  255,  102,  158,  159,

       98,   40,   31,  258,   32,  104,  257,   33,  102,   34,
       78,   98,   35,   36,  102,  102,  104,   98,   98,  138,
      256,   37,  104,  104,  134,  134,   38,   39,  139,  102,
      102,  102,   98,   98,   98,  106,  107,  104,  104,  104,
      102,   40,   20,   98,  253,   41,  105,  252,  104,   26,
      108,  115,   42,   43,  102,  102,  251,   98,   98,  250,
      249,  116,  104,  104,   44,  248,   45,   46,   86,   87,
       87,   86,   88,   88,  247,  117,  118,  246,   47,  245,
       48,   49,   50,   51,   52,   25,   20,   25,   25,   25,
       25,   25,   25,   26,   25,   25,   53,   54,   25,   25,

       25,   55,   55,   55,   25,   25,   25,   56,   55,   57,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   58,  244,   59,   60,   61,   98,  101,  101,
      102,  243,  185,   98,  102,   62,   63,   98,  104,   64,
      186,  242,  104,  241,  102,   65,   58,   98,   59,   60,
       61,  240,  104,  102,  102,  239,   98,   98,  238,   62,
       63,  104,  104,   64,  146,  102,  186,  237,   98,   65,
       20,  236,   66,  104,  102,  102,  235,   98,   98,   67,
       68,   68,  104,  104,  233,   68,  232,  231,   69,  230,

       70,  147,   68,   68,   68,   68,   68,   68,  102,  151,
      102,   98,  150,   98,  148,  228,  104,  227,  104,  226,
      102,  149,  152,   98,  109,  110,  111,  112,  104,  225,
      102,  102,  113,   98,   98,  185,  187,  187,  104,  104,
      153,  114,   98,  145,  145,  223,  102,  222,  145,   98,
      185,  187,  187,  221,  104,  145,  145,  145,  145,  145,
      145,  102,  220,  164,   98,  165,  219,  218,  217,  104,
      154,  102,  102,  215,   98,   98,  155,  166,  102,  104,
      104,   98,  167,  214,  102,  102,  104,   98,   98,  213,
      212,  182,  104,  104,  102,  102,  102,   98,   98,   98,

      211,  210,  104,  104,  104,  102,  102,  102,   98,   98,
       98,  209,  205,  104,  104,  104,  102,  204,  102,   98,
      202,   98,  102,  201,  104,   98,  104,  200,  199,  198,
      104,  197,  216,  196,  203,  185,  207,  207,  195,  102,
      194,  207,   98,  229,  193,  234,  192,  104,  207,  207,
      207,  207,  207,  207,  191,  224,   20,   20,   20,   20,
       20,   20,   25,   25,   25,   25,   25,   25,   30,   30,
       30,   30,   30,   30,   99,   99,   99,  103,  103,  103,
      103,  144,  144,  104,  190,  104,  104,  160,  160,  161,
      189,  161,  161,  161,  161,  162,  162,  206,  206,  208,

      208,  188,  185,  184,  183,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  171,  170,  168,  163,  157,
      156,  102,   98,  143,  142,  141,  140,  137,  136,  135,
      133,  132,  131,  125,  124,  123,  122,  121,  119,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   89,   85,
       84,   83,   82,   81,   80,  267,   19,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  267,  267
    } ;

static yyconst flex_int16_t yy_chk[605] =
    {   0,
        0,    0,    0,    0,  281,  275,  274,    3,  273,    1,
       15,    1,    1,    2,    3,    2,    2,    3,  265,    4,
       15,   15,   16,    0,    1,   17,    4,   18,    2,    4,
       21,    0,   16,   16,   22,   17,   17,   18,   18,   23,
       23,  264,   27,  262,   21,    3,   21,  261,   35,    3,
       36,   36,   72,   72,   21,  260,   73,    4,   53,   80,
       22,    4,    5,  259,    5,   80,   53,    5,   27,    5,
       79,   79,    5,    5,   35,   80,   42,   42,   42,   86,
       86,    5,   73,  258,   42,  257,    5,    5,   43,   43,
       43,  253,   53,   54,   54,   54,  253,   55,  123,  123,

       55,    5,    6,  256,    6,   55,  255,    6,   57,    6,
       42,   57,    6,    6,   58,   59,   57,   58,   59,   93,
      254,    6,   58,   59,  134,  134,    6,    6,   93,   60,
       62,  103,   60,   62,  103,   58,   59,   60,   62,  103,
       63,    6,    7,   63,  252,    7,   57,  251,   63,    7,
       60,   62,    7,    7,   64,   65,  249,   64,   65,  248,
      247,   63,   64,   65,    7,  246,    7,    7,   87,   87,
       87,   88,   88,   88,  245,   64,   65,  243,    7,  242,
        7,    7,    7,    7,    7,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   11,  241,   11,   11,   11,  101,  101,  101,
      105,  240,  158,  105,  106,   11,   11,  106,  105,   11,
      158,  238,  106,  237,  107,   11,   12,  107,   12,   12,
       12,  236,  107,  108,  109,  234,  108,  109,  233,   12,
       12,  108,  109,   12,  105,  111,  158,  232,  111,   12,
       13,  231,   13,  111,  110,  112,  230,  110,  112,   13,
       13,   13,  110,  112,  228,   13,  227,  226,   13,  225,

       13,  109,   13,   13,   13,   13,   13,   13,   61,  112,
      113,   61,  111,  113,  110,  223,   61,  221,  113,  220,
      115,  110,  112,  115,   61,   61,   61,   61,  115,  219,
      116,  117,   61,  116,  117,  159,  159,  159,  116,  117,
      113,   61,  100,  100,  100,  215,  114,  214,  100,  114,
      187,  187,  187,  212,  114,  100,  100,  100,  100,  100,
      100,  118,  211,  128,  118,  128,  209,  205,  204,  118,
      114,  146,  147,  202,  146,  147,  114,  128,  148,  146,
      147,  148,  128,  201,  149,  150,  148,  149,  150,  200,
      199,  146,  149,  150,  151,  152,  153,  151,  152,  153,

      198,  197,  151,  152,  153,  154,  155,  182,  154,  155,
      182,  196,  184,  154,  155,  182,  203,  183,  224,  203,
      180,  224,  216,  179,  203,  216,  224,  178,  177,  176,
      216,  175,  203,  174,  182,  186,  186,  186,  173,  229,
      171,  186,  229,  224,  170,  229,  167,  229,  186,  186,
      186,  186,  186,  186,  166,  216,  268,  268,  268,  268,
      268,  268,  269,  269,  269,  269,  269,  269,  270,  270,
      270,  270,  270,  270,  271,  271,  271,  272,  272,  272,
      272,  276,  276,  277,  165,  277,  277,  278,  278,  279,
      164,  279,  279,  279,  279,  280,  280,  282,  282,  283,

      283,  162,  160,  157,  156,  144,  143,  142,  141,  140,
      139,  137,  136,  135,  133,  132,  131,  129,  127,  122,
      121,  104,   99,   97,   96,   95,   94,   92,   91,   89,
       85,   84,   83,   77,   76,   75,   74,   69,   67,   56,
       52,   51,   50,   49,   48,   47,   46,   45,   44,   40,
       39,   38,   37,   28,   24,   19,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  267,

      267,  267,  267,  267
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "opts.l"
#line 2 "opts.l"
#include <assert.h>

#include "stuff.h"
#include "dmalloc.h"
#include "X86_register.h"

#include "y.tab.h"
#include "opts.h"

void print_current_state();



#line 697 "opts.lex.c"

#define INITIAL 0
#define STATE_BPM 1
#define STATE_BPX 2
#define STATE_BPF 3
#define STATE_ADDRESS 4
#define STATE_ADDRESS_OR_REG 5
#define STATE_BYTEMASK 6
#define STATE_BYTEMASK_SKIP_OPT 7
#define STATE_READ_ADR_OFS 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 25 "opts.l"


#line 905 "opts.lex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 268 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 557 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 27 "opts.l"
{ BEGIN(STATE_BPX); yy_push_state(STATE_ADDRESS); return BPX_EQ; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 28 "opts.l"
{ assert (current_BPF==NULL); current_BPF=DCALLOC (BPF, 1, "BPF"); current_BPF->rt_probability=1; BEGIN(STATE_BPF); yy_push_state(STATE_ADDRESS); return BPF_EQ; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "opts.l"
{ yylval.num=1; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 30 "opts.l"
{ yylval.num=2; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "opts.l"
{ yylval.num=4; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 32 "opts.l"
{ yylval.num=8; BEGIN(STATE_BPM); yy_push_state(STATE_ADDRESS); return BPM_width; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 33 "opts.l"
{ yylval.str=DSTRDUP(yytext+3, "yytext"); return LOAD_FILENAME; };
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 34 "opts.l"
{ yylval.num=strtol(yytext+3, NULL, 10); return ATTACH_PID; };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 35 "opts.l"
{ yylval.num=strtol(yytext+3, NULL, 16); return ATTACH_PID; };
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 36 "opts.l"
{ yylval.str=DSTRDUP(yytext+3, "yytext"); return ATTACH_FILENAME; };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "opts.l"
{ yylval.str=DSTRDUP(yytext+3, "yytext"); return CMDLINE; };
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 38 "opts.l"
{ return CHILD; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "opts.l"
{ yylval.x86reg=R_EAX; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "opts.l"
{ yylval.x86reg=R_EBX; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "opts.l"
{ yylval.x86reg=R_ECX; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "opts.l"
{ yylval.x86reg=R_EDX; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "opts.l"
{ yylval.x86reg=R_ESI; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "opts.l"
{ yylval.x86reg=R_EDI; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "opts.l"
{ yylval.x86reg=R_EBP; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "opts.l"
{ yylval.x86reg=R_ESP; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "opts.l"
{ yylval.x86reg=R_EIP; yy_pop_state(); return REGISTER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "opts.l"
{ yylval.x86reg=R_PF;  yy_pop_state(); return REGISTER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "opts.l"
{ yylval.x86reg=R_SF;  yy_pop_state(); return REGISTER; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "opts.l"
{ yylval.x86reg=R_AF;  yy_pop_state(); return REGISTER; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "opts.l"
{ yylval.x86reg=R_ZF;  yy_pop_state(); return REGISTER; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "opts.l"
{ yylval.x86reg=R_OF;  yy_pop_state(); return REGISTER; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "opts.l"
{ yylval.x86reg=R_CF;  yy_pop_state(); return REGISTER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "opts.l"
{ yylval.x86reg=R_DF;  yy_pop_state(); return REGISTER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "opts.l"
{ yy_push_state(STATE_BYTEMASK); return BYTEMASK; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "opts.l"
{ yylval.num = strtol(yytext, NULL, 16); return HEX_BYTE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "opts.l"
{ yy_push_state(STATE_BYTEMASK_SKIP_OPT); return SKIP; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "opts.l"
{ return TWO_POINTS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "opts.l"
{ 
    if (YYSTATE==STATE_BYTEMASK)
    {
        yy_pop_state(); /* switch back to STATE_ADDRESS */
        yy_pop_state(); /* switch back to what was before */
    };
    return BYTEMASK_END; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "opts.l"
{ return R_SQUARE_BRACKET; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "opts.l"
{
    if ((YYSTATE==STATE_ADDRESS) || (YYSTATE==STATE_READ_ADR_OFS))
        yy_pop_state(); /* switch back to what was before STATE_ADDRESS */
    yylval.num = strtol(yytext, NULL, 16); 
    return HEX_NUMBER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "opts.l"
{ 
    if (YYSTATE==STATE_READ_ADR_OFS || YYSTATE==STATE_BYTEMASK_SKIP_OPT)
        yy_pop_state(); /* switch back to what was before STATE_ADDRESS */
    yylval.num = strtol(yytext, NULL, 10); 
    return DEC_NUMBER; 
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 81 "opts.l"
{ 
    yylval.dbl = atof(yytext); 
    return FLOAT_NUMBER; 
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 85 "opts.l"
{ yylval.str = DSTRDUP(yytext, "yytext"); str_trim_one_char_right(yylval.str); return FILENAME_EXCLAMATION; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 86 "opts.l"
{ 
    BEGIN (STATE_READ_ADR_OFS);
    yylval.str = DSTRDUP(yytext, "yytext");
    str_trim_one_char_right(yylval.str);
    return SYMBOL_NAME_PLUS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "opts.l"
{ 
    yy_pop_state(); /* switch back to what was before STATE_ADDRESS */
    yylval.str = DSTRDUP(yytext, "yytext"); 
    return SYMBOL_NAME; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 96 "opts.l"
{ return COMMA; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 97 "opts.l"
{ return W; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 98 "opts.l"
{ return RW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "opts.l"
{ yy_push_state(STATE_ADDRESS_OR_REG); return DUMP_OP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 101 "opts.l"
{ yy_push_state(STATE_ADDRESS_OR_REG); return SET_OP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 102 "opts.l"
{ yy_push_state(STATE_ADDRESS_OR_REG); return COPY_OP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 103 "opts.l"
{ return CP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 104 "opts.l"
{ return QUOTE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 105 "opts.l"
{ yylval.num = strtol(yytext+2, NULL, 16); return CSTRING_BYTE ; }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 106 "opts.l"
{ yylval.num = yytext[0]; return CSTRING_BYTE ; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 107 "opts.l"
{ return BPF_UNICODE; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 108 "opts.l"
{ return BPF_TRACE_COLON; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 109 "opts.l"
{ return BPF_TRACE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 110 "opts.l"
{ return BPF_SKIP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 111 "opts.l"
{ return BPF_SKIP_STDCALL; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 112 "opts.l"
{ return BPF_PAUSE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 113 "opts.l"
{ return BPF_RT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 114 "opts.l"
{ return BPF_RT_PROBABILITY; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 115 "opts.l"
{ return BPF_ARGS; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 116 "opts.l"
{ return BPF_CC; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 117 "opts.l"
{ return PERCENT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 118 "opts.l"
{ return BPF_DUMP_ARGS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 119 "opts.l"
{ yy_push_state(STATE_ADDRESS); return WHEN_CALLED_FROM_ADDRESS; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 120 "opts.l"
{ yy_push_state(STATE_ADDRESS); return WHEN_CALLED_FROM_FUNC; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 121 "opts.l"
{ fprintf (stderr, "Unrecognized symbol: '%c'\n", yytext[0]); return yytext[0]; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 122 "opts.l"
ECHO;
	YY_BREAK
#line 1344 "opts.lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STATE_BPM):
case YY_STATE_EOF(STATE_BPX):
case YY_STATE_EOF(STATE_BPF):
case YY_STATE_EOF(STATE_ADDRESS):
case YY_STATE_EOF(STATE_ADDRESS_OR_REG):
case YY_STATE_EOF(STATE_BYTEMASK):
case YY_STATE_EOF(STATE_BYTEMASK_SKIP_OPT):
case YY_STATE_EOF(STATE_READ_ADR_OFS):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 268 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 268 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 267);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "opts.l"



//<STATE_BPX><<EOF>> { return _EOF; }
// [ \t]                    { /* ignore comment and white space */ }
// ":"                      { return COLON; }
// \n                       { return EOL; }
/* <STATE_ADDRESS>"+"                        { return PLUS; } */
// .                        { fprintf(stderr, "Unparsed character %c\n", *yytext); }
void flex_set_str(char *s)
{
    YY_BUFFER_STATE buf;
    buf=yy_scan_string (s);
    yy_switch_to_buffer (buf);
};

void flex_cleanup()
{
    yy_delete_buffer(YY_CURRENT_BUFFER );
};

void flex_restart()
{
    BEGIN(INITIAL);
};

